const CONFIG = { baseParticles:105, maxBursts:14, trailLimit:24, colors:['#ffc16d','#ff9659','#f06c65','#ffe4a6','#d94f55'], glow:['#ff9b53','#ffc477','#f17869'], pulseSeconds:1.55, petalScale:1 };
const rand=(a,b)=>a+Math.random()*(b-a);
class World {
 constructor(canvas,portrait){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:true});this.portrait=portrait;this.w=1;this.h=1;this.dpr=1;this.progress=0;this.pointer={x:.5,y:.5};this.target={x:.5,y:.5};this.particles=[];this.trails=[];this.bursts=[];this.last=0;this.elapsed=0;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.count=CONFIG.baseParticles;this.resize=this.resize.bind(this);addEventListener('resize',this.resize,{passive:true});this.resize();this.seed();}
 resize(){this.w=innerWidth;this.h=innerHeight;this.dpr=Math.min(devicePixelRatio||1,1.65);this.canvas.width=Math.round(this.w*this.dpr);this.canvas.height=Math.round(this.h*this.dpr);this.canvas.style.width=this.w+'px';this.canvas.style.height=this.h+'px';this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.count=this.w<700?60:CONFIG.baseParticles;}
 seed(){for(let i=0;i<this.count;i++)this.particles.push(this.makeParticle(true));}
 makeParticle(seed=false){return{a:rand(0,Math.PI*2),r:rand(.11,.48),speed:rand(.025,.13),size:rand(.6,2.3),phase:rand(0,7),hue:Math.floor(rand(0,CONFIG.colors.length)),life:seed?rand(0,1):0};}
 setPointer(x,y){this.target.x=x/this.w;this.target.y=y/this.h;}
 burst(x,y){const amount=this.w<700?18:28;this.bursts.push(...Array.from({length:amount},()=>({x,y,vx:rand(-1.4,1.4),vy:rand(-2.2,.6),size:rand(1.2,3.4),life:1,color:CONFIG.colors[Math.floor(rand(0,CONFIG.colors.length))],spin:rand(0,7)})));if(this.bursts.length>750)this.bursts.splice(0,this.bursts.length-750);}
 drawGlow(x,y,radius,color,alpha){const c=this.ctx,g=c.createRadialGradient(x,y,0,x,y,radius);g.addColorStop(0,color);g.addColorStop(.17,color);g.addColorStop(1,'rgba(0,0,0,0)');c.globalAlpha=alpha;c.fillStyle=g;c.fillRect(x-radius,y-radius,radius*2,radius*2);c.globalAlpha=1;}
 draw(time){if(this.reduced){this.staticFrame();return;}const c=this.ctx,dt=Math.min(.04,(time-(this.last||time))/1000);this.last=time;this.elapsed+=dt;this.pointer.x+=(this.target.x-this.pointer.x)*.035;this.pointer.y+=(this.target.y-this.pointer.y)*.035;const p=this.progress,cx=this.w*(.5+(this.pointer.x-.5)*.045),cy=this.h*(.38+(this.pointer.y-.5)*.045);c.clearRect(0,0,this.w,this.h);const meet=Math.min(1,Math.max(0,(p-.045)/.14)),sep=(1-meet)*Math.min(this.w,this.h)*.28,wander=Math.sin(this.elapsed*.31)*13;this.drawGlow(cx-sep*.5+wander,cy,Math.max(82,this.w*.25),'#e99052',.24+meet*.16);this.drawGlow(cx+sep*.5-wander,cy+Math.cos(this.elapsed*.27)*11,Math.max(82,this.w*.25),'#db8263',.22+meet*.16);const pulse=1+.065*Math.sin(this.elapsed*(2*Math.PI/CONFIG.pulseSeconds))+.018*Math.sin(this.elapsed*4.1),strength=Math.max(0,Math.min(1,(p-.18)/.38));this.drawGlow(cx,cy,(24+strength*190)*pulse,'#ffb866',.06+strength*.3);this.drawGlow(cx,cy,(12+strength*60)*pulse,'#ffdaa0',.08+strength*.32);this.drawPetals(cx,cy,Math.max(0,Math.min(1,(p-.31)/.4)),dt);this.drawConstellation(cx,cy,p,dt);this.drawParticles(cx,cy,p,dt);this.drawBursts(dt);this.portrait.style.opacity=String(.94+Math.min(.06,strength*.06));this.portrait.style.transform='scale('+(1.035-Math.min(.018,Math.max(0,p-.72)*.025))+')';}
 drawPetals(cx,cy,amount){if(!amount)return;const c=this.ctx,spin=this.elapsed*.035;for(let i=0;i<9;i++){const a=i*Math.PI*2/9+spin+Math.sin(this.elapsed*.16+i)*.07,r=(54+((i*37)%73))*amount,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r*.68,bloom=Math.min(1,Math.max(0,(this.elapsed-i*.43)*.38))*amount;c.save();c.translate(x,y);c.rotate(a+.65);c.scale(bloom,bloom);c.globalAlpha=.2+amount*.26;c.fillStyle=CONFIG.colors[i%CONFIG.colors.length];c.shadowBlur=22;c.shadowColor=c.fillStyle;c.beginPath();c.ellipse(0,-17,9,23,0,0,Math.PI*2);c.fill();c.restore();}}
 drawConstellation(cx,cy,p){const amount=Math.max(0,Math.min(1,(p-.48)/.4));if(!amount)return;const c=this.ctx,points=12;for(let i=0;i<points;i++){const a=i*2.399+Math.sin(this.elapsed*.12+i)*.035,r=(.14+((i*17)%11)/60)*Math.min(this.w,this.h),x=cx+Math.cos(a)*r+(this.pointer.x-.5)*18,y=cy+Math.sin(a)*r*.7+(this.pointer.y-.5)*18,j=(i+1)%points,b=j*2.399+Math.sin(this.elapsed*.12+j)*.035,rr=(.14+((j*17)%11)/60)*Math.min(this.w,this.h);c.beginPath();c.moveTo(x,y);c.lineTo(cx+Math.cos(b)*rr+(this.pointer.x-.5)*18,cy+Math.sin(b)*rr*.7+(this.pointer.y-.5)*18);c.strokeStyle='rgba(255,205,150,'+(.1*amount)+')';c.lineWidth=.7;c.stroke();c.beginPath();c.arc(x,y,1.6+amount,0,Math.PI*2);c.fillStyle='rgba(255,220,173,'+(.38*amount)+')';c.fill();}}
 drawParticles(cx,cy,p,dt){const c=this.ctx,activate=Math.max(0,Math.min(1,(p-.12)/.3));this.particles.forEach(o=>{o.a+=o.speed*dt;o.life=Math.min(1,o.life+dt*.22);const spread=(.1+activate*.48)*Math.min(this.w,this.h),r=o.r*spread,x=cx+Math.cos(o.a+o.phase)*r+(this.pointer.x-.5)*o.r*28,y=cy+Math.sin(o.a*1.13+o.phase)*r*.7-this.elapsed*(8+o.speed*55)%this.h;let yy=y;if(yy<0)yy+=this.h;const alpha=(.16+activate*.62)*o.life*(.65+.35*Math.sin(this.elapsed*2+o.phase));c.beginPath();c.arc(x,yy,o.size,0,Math.PI*2);c.fillStyle=CONFIG.colors[o.hue];c.globalAlpha=alpha;c.shadowBlur=11;c.shadowColor=c.fillStyle;c.fill();c.shadowBlur=0;c.globalAlpha=1;});}
 drawBursts(dt){const c=this.ctx;this.trails.forEach(t=>{t.life-=dt*.85;if(t.life>0)this.drawGlow(t.x,t.y,28,t.color,t.life*.32);});this.trails=this.trails.filter(t=>t.life>0);this.bursts.forEach(b=>{b.x+=b.vx;b.y+=b.vy;b.vy+=.012;b.life-=dt*.72;if(b.life<=0)return;c.save();c.translate(b.x,b.y);c.rotate(b.spin+b.life);c.globalAlpha=b.life;c.fillStyle=b.color;c.shadowBlur=12;c.shadowColor=b.color;c.beginPath();c.ellipse(0,0,b.size*.55,b.size*1.6,0,0,Math.PI*2);c.fill();c.restore();});this.bursts=this.bursts.filter(b=>b.life>0);}
 staticFrame(){const c=this.ctx,p=this.progress,cx=this.w/2,cy=this.h*.38;c.clearRect(0,0,this.w,this.h);this.drawGlow(cx,cy,Math.min(this.w,this.h)*.34,'#ffb866',.35);const stage=Math.floor(p*3);if(stage>0)this.drawPetals(cx,cy,1,0);if(stage>1)this.drawConstellation(cx,cy,1,0);this.portrait.style.opacity=String(.94+Math.min(.06,Math.max(0,(p-.2)*.08)));}
}
window.LoveWorld={World,CONFIG};
